version: "3"
services:
  app1:
    image: alpine
    command: sh -c "apk add --no-cache iputils && sleep infinity"
    networks:
      - my_network

  app2:
    image: alpine
    command: sh -c "apk add --no-cache iputils && sleep infinity"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

